# Generated by Django 5.1.3 on 2024-11-26 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas_Saber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe a área do saber:', max_length=255, verbose_name='Áreas do Saber')),
            ],
        ),
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o nome da cidade', max_length=255, verbose_name='Nome da Cidade')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Ocupacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o nome da ocupação', max_length=255, unique=True, verbose_name='Nome da Ocupação')),
            ],
            options={
                'verbose_name': 'Ocupação',
                'verbose_name_plural': 'Ocupações',
            },
        ),
        migrations.CreateModel(
            name='tipoavaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o nome da turma:', max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o turno:', max_length=255, verbose_name='Turnos')),
            ],
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(help_text='Informe a sigla da Unidade Federativa', max_length=2, unique=True, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Unidade Federal',
                'verbose_name_plural': 'Unidades Federais',
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o curso:', max_length=255, verbose_name='Cursos')),
                ('carga_horaria_total', models.CharField(help_text='Informe a carga horária total', max_length=255, verbose_name='Carga Horária Total')),
                ('duracao_meses', models.CharField(help_text='Informe a duração em meses', max_length=255, verbose_name='Duração em meses')),
                ('Areas_Saber', models.ForeignKey(blank=True, help_text='Selecione a área do saber', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.areas_saber', verbose_name='Áreas do Saber')),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o nome', max_length=255, verbose_name='Nome')),
                ('site', models.CharField(help_text='Informe o site', max_length=255, verbose_name='Site')),
                ('telefone', models.CharField(help_text='Informe o telefone', max_length=255, verbose_name='Telefone')),
                ('cidades', models.ForeignKey(blank=True, help_text='Selecione a cidade', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cidades', verbose_name='Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe as disciplinas:', max_length=255, verbose_name='Displinas')),
                ('Instituicao', models.ForeignKey(blank=True, help_text='Selecione a instituição', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.instituicao', verbose_name='Instituição')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o nome', max_length=255, verbose_name='Nome')),
                ('nome_pai', models.CharField(help_text='Informe o nome do pai', max_length=255, verbose_name='Nome do Pai')),
                ('nome_mae', models.CharField(help_text='Informe o nome da mãe', max_length=255, verbose_name='Nome da Mãe')),
                ('cpf', models.CharField(help_text='Informe o CPF', max_length=11, unique=True, verbose_name='CPF')),
                ('data_nasc', models.DateField(default='2000-01-01', help_text='Informe a data de Nascimento', verbose_name='Data de Nascimento')),
                ('email', models.EmailField(help_text='Informe o e-mail', max_length=254, verbose_name='E-mail')),
                ('Ocupacoes', models.ForeignKey(blank=True, help_text='Selecione a ocupação', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ocupacoes', verbose_name='Ocupação')),
                ('cidades', models.ForeignKey(blank=True, help_text='Selecione a cidade', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cidades', verbose_name='Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='Descreva a ocorrência', verbose_name='Descrição')),
                ('data', models.DateField(help_text='Informe a data da ocorrência', verbose_name='Data da Ocorrência')),
                ('curso', models.ForeignKey(help_text='Selecione o curso relacionado à ocorrência', on_delete=django.db.models.deletion.CASCADE, to='app.cursos', verbose_name='Curso')),
                ('disciplina', models.ForeignKey(help_text='Selecione a disciplina relacionada à ocorrência', on_delete=django.db.models.deletion.CASCADE, to='app.disciplinas', verbose_name='Disciplina')),
                ('pessoa', models.ForeignKey(help_text='Selecione a pessoa relacionada à ocorrência', on_delete=django.db.models.deletion.CASCADE, to='app.pessoas', verbose_name='Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matricula', models.CharField(help_text='Informe a matrícula:', max_length=255, verbose_name='Matrícula')),
                ('data_inicio', models.DateField(default='2000-01-01', help_text='Informe a data de início', verbose_name='Data de início')),
                ('data_previsao_termino', models.DateField(default='2000-01-01', help_text='Informe a data de previsão do término', verbose_name='Data de previsão do término')),
                ('Cursos', models.ForeignKey(blank=True, help_text='Selecione o curso', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cursos', verbose_name='Cursos')),
                ('Instituicao', models.ForeignKey(blank=True, help_text='Selecione a instituição', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.instituicao', verbose_name='Instituição')),
                ('Pessoas', models.ForeignKey(blank=True, help_text='Selecione o usuário', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pessoas', verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_faltas', models.CharField(help_text='Informe as faltas:', max_length=255, verbose_name='Faltas')),
                ('Cursos', models.ForeignKey(blank=True, help_text='Selecione o curso', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cursos', verbose_name='Cursos')),
                ('Disciplinas', models.ForeignKey(blank=True, help_text='Selecione a disciplina', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.disciplinas', verbose_name='Disciplinas')),
                ('Pessoas', models.ForeignKey(blank=True, help_text='Selecione o usuário', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pessoas', verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o nome da turma:', max_length=255, verbose_name='Nome')),
                ('Turnos', models.ForeignKey(blank=True, help_text='Selecione o turno', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.turnos', verbose_name='Turno')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaPorCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria', models.PositiveIntegerField(help_text='Informe a carga horária em horas', verbose_name='Carga Horária')),
                ('curso', models.ForeignKey(help_text='Selecione o curso', on_delete=django.db.models.deletion.CASCADE, to='app.cursos', verbose_name='Curso')),
                ('disciplina', models.ForeignKey(help_text='Selecione a disciplina', on_delete=django.db.models.deletion.CASCADE, to='app.disciplinas', verbose_name='Disciplina')),
                ('turno', models.ForeignKey(help_text='Selecione o turno', on_delete=django.db.models.deletion.CASCADE, to='app.turnos', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Disciplina por Curso',
                'verbose_name_plural': 'Disciplinas por Cursos',
            },
        ),
        migrations.AddField(
            model_name='cidades',
            name='uf',
            field=models.ForeignKey(blank=True, help_text='Selecione a Unidade Federal', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.uf', verbose_name='Unidade Federal'),
        ),
        migrations.AlterUniqueTogether(
            name='cidades',
            unique_together={('nome', 'uf')},
        ),
    ]
