# Generated by Django 5.1.3 on 2024-11-26 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriculas',
            name='Cursos',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='Cursos',
        ),
        migrations.AlterModelOptions(
            name='disciplinaporcurso',
            options={'verbose_name': 'Disciplina por Curso', 'verbose_name_plural': 'Disciplinas por curso'},
        ),
        migrations.RenameField(
            model_name='disciplinas',
            old_name='Instituicao',
            new_name='instituicao',
        ),
        migrations.RenameField(
            model_name='frequencia',
            old_name='Disciplinas',
            new_name='disciplina',
        ),
        migrations.RenameField(
            model_name='frequencia',
            old_name='Pessoas',
            new_name='pessoas',
        ),
        migrations.RenameField(
            model_name='matriculas',
            old_name='Instituicao',
            new_name='instituicao',
        ),
        migrations.RenameField(
            model_name='matriculas',
            old_name='Matricula',
            new_name='matricula',
        ),
        migrations.RenameField(
            model_name='matriculas',
            old_name='Pessoas',
            new_name='pessoas',
        ),
        migrations.RenameField(
            model_name='pessoas',
            old_name='Ocupacoes',
            new_name='ocupacao',
        ),
        migrations.RenameField(
            model_name='turmas',
            old_name='Turnos',
            new_name='turnos',
        ),
        migrations.RenameModel(
            old_name='Areas_Saber',
            new_name='Area_Saber',
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o curso:', max_length=255, verbose_name='curso')),
                ('carga_horaria_total', models.CharField(help_text='Informe a carga horária total', max_length=255, verbose_name='Carga Horária Total')),
                ('duracao_meses', models.CharField(help_text='Informe a duração em meses', max_length=255, verbose_name='Duração em meses')),
                ('area_saber', models.ForeignKey(blank=True, help_text='Selecione a área do saber', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.area_saber', verbose_name='Áreas do Saber')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Informe a descricao:', max_length=255, verbose_name='Descricao')),
                ('nota', models.CharField(help_text='Informe a nota:', max_length=255, verbose_name='Nota')),
                ('disciplina', models.ForeignKey(blank=True, help_text='Selecione a disciplina', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.disciplinas', verbose_name='Disciplinas')),
                ('tipoavaliacao', models.ForeignKey(blank=True, help_text='Selecione o tipo da avaliação', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pessoas', verbose_name='Tipo de avaliação')),
                ('curso', models.ForeignKey(blank=True, help_text='Selecione o curso', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='curso')),
            ],
        ),
        migrations.AddField(
            model_name='frequencia',
            name='curso',
            field=models.ForeignKey(blank=True, help_text='Selecione o curso', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='curso'),
        ),
        migrations.AddField(
            model_name='matriculas',
            name='curso',
            field=models.ForeignKey(blank=True, help_text='Selecione o curso', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='curso'),
        ),
        migrations.AlterField(
            model_name='disciplinaporcurso',
            name='curso',
            field=models.ForeignKey(help_text='Selecione o curso', on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='curso',
            field=models.ForeignKey(help_text='Selecione o curso relacionado à ocorrência', on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso'),
        ),
        migrations.DeleteModel(
            name='Cursos',
        ),
    ]
