# Generated by Django 5.1.3 on 2024-11-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_matriculas_cursos_remove_frequencia_cursos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplinaporcurso',
            options={},
        ),
    ]
