# Generated by Django 5.1.3 on 2024-12-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_disciplinas_options_alter_frequencia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area_saber',
            options={'verbose_name': 'Área do saber', 'verbose_name_plural': 'Áreas do saber'},
        ),
    ]
