# Generated by Django 5.1.3 on 2024-12-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_matricula_matriculas_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequencia',
            old_name='numero_faltas',
            new_name='nome',
        ),
    ]
