# Generated by Django 5.1.3 on 2024-12-17 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_numero_faltas_frequencia_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocorrencia',
            old_name='descricao',
            new_name='nome',
        ),
    ]
